@startuml

class IInterface
abstract class AbstractImpl
note right: 空实现了 IInterface 的全部接口
class FinalImplClass
note right: 继承 AbstractImpl 只实现自己需要的方法

AbstractImpl ..|> IInterface
FinalImplClass --|> AbstractImpl

class FinalImplClass {
    + method1():void
    + method2():void
}

interface AbstractImpl {
    + method1():void
    + method2():void
    + method3():void
    + method4():void
}

interface IInterface {
    + method1():void
    + method2():void
    + method3():void
    + method4():void
}

@enduml