@startuml

class Order

interface IOrderCreate {
    +createOrder(Order order):Order
}
interface IOrderCancle {
    +cancle(Order order):Order
}
interface IOrderPayPrepare {
    +payPrepare (Order order):Order
}
interface IOrderPaySuccess {
    +paySuccess(Order order):Order
}
interface IOrderDefray {
    +orderDefray(Order order):Order
}
interface IOrderPayFail {
    +payFail(Order order):Order
}
interface IOrderRefund {
    +refund(Order order):Order
}

IOrderCreate ..> Order
IOrderCancle ..> Order
IOrderPayPrepare ..> Order
IOrderPaySuccess ..> Order
IOrderDefray ..> Order
IOrderPayFail ..> Order
IOrderRefund ..> Order

TicketChargeOrderExecutor --|> OrderLifeCycleExecutor

TicketChargeOrderCreate <.. TicketChargeOrderExecutor
TicketChargeOrderCancle <.. TicketChargeOrderExecutor
TicketChargeOrderPayPrepare <.. TicketChargeOrderExecutor
TicketChargeOrderPaySuccess <.. TicketChargeOrderExecutor
TicketChargeOrderDefray <.. TicketChargeOrderExecutor
TicketChargeOrderPayFail <.. TicketChargeOrderExecutor
TicketChargeOrderRefund <.. TicketChargeOrderExecutor

OrderLifeCycleExecutor o.. IOrderCreate
OrderLifeCycleExecutor o.. IOrderCancle
OrderLifeCycleExecutor o.. IOrderPayPrepare
OrderLifeCycleExecutor o.. IOrderPaySuccess
OrderLifeCycleExecutor o.. IOrderDefray
OrderLifeCycleExecutor o.. IOrderPayFail
OrderLifeCycleExecutor o.. IOrderRefund

TicketChargeOrderCreate ..|> IOrderCreate
TicketChargeOrderCancle ..|> IOrderCancle
TicketChargeOrderPayPrepare ..|> IOrderPayPrepare
TicketChargeOrderPaySuccess ..|> IOrderPaySuccess
TicketChargeOrderDefray ..|> IOrderDefray
TicketChargeOrderPayFail ..|> IOrderPayFail
TicketChargeOrderRefund ..|> IOrderRefund

class Order {

}

abstract class OrderLifeCycleExecutor {
    -orderCreateExecutor:IOrderCreate
    -orderCancleExecutor:IOrderCancle
    -orderPayPrepareExecutor:IOrderPayPrepare
    -orderPaySuccessExecutor:IOrderPaySuccess
    -orderOrderDefrayExecutor:IOrderDefray
    -orderOrderPayFailExecutor:IOrderPayFail
    -orderOrderRefundExecutor:IOrderRefund

    +setOrderCreateExecutor(IOrderCreate):void
    +setOrderCancleExecutor(IOrderCancle):void
    +setOrderPayPrepareExecutor(IOrderPayPrepare):void
    +setOrderPaySuccessExecutor(IOrderPaySuccess):void
    +setOrderOrderDefrayExecutor(IOrderDefray):void
    +setOrderOrderPayFailExecutor(IOrderPayFail):void
    +setOrderOrderRefundExecutor(IOrderRefund):void
}

@enduml