@startuml

class Client
class Calculator
abstract class Expression
class VarExpression
class SymbolExpression
class SubExpression
class AddExpression

VarExpression --|> Expression

SymbolExpression --|> Expression

AddExpression --|> SymbolExpression
SubExpression --|> SymbolExpression

Expression --o SymbolExpression
Expression --o Calculator

Client ..> Calculator

abstract class Expression {
    +interpreter()
}

@enduml