@startuml

abstract class Drink
abstract class Coffee
abstract class Decorator

Drink <|-- Coffee
Drink <|-- Decorator

class Drink {
    -price:float
    -description:String
    +getDesc()
    +getCost()
}

@enduml