@startuml

abstract class Component
note left : <size:10>Component 为所有节点的基类，不管是普通节点还是叶子节点
class Composite
note left : <size:10>组合可以操作子节点或者叶子节点，但可能不具有叶子节点的某些行为
class Leaf
note left : <size:10>叶子节点，不能操作子节点

Composite --|> Component
Composite o-- Component
Leaf --|> Component

abstract class Component {
    +add(component:Component):void
    +remove(component:Component):void
    +getChild():int
    +operation():void
}

class Composite {
    +add(component:Component):void
    +remove(component:Component):void
    +getChild():int
    +operation():void
}

class Leaf {
    +operation():void
}

abstract class OrganizationComponent
class University
class College
class Department
class Client

Client ..> OrganizationComponent

OrganizationComponent <|-- University
OrganizationComponent <|-- College
OrganizationComponent <|-- Department

OrganizationComponent --o University
OrganizationComponent --o College


abstract class OrganizationComponent {
    +add(component:OrganizationComponent):void
    +print():void
}


@enduml