@startuml

Interface Map
Interface Entry
abstract class AbstractMap
class HashMap
class Node

AbstractMap ..|> Map
Node ..|> Entry
HashMap --|> AbstractMap
Node --* HashMap
Entry --* AbstractMap

@enduml